name: gaussian_splatting
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=12.1
  - plyfile=1.0.2
  - python=3.11.6
  - pip=23.3.1
  - pytorch=2.1.1
  - torchvision=0.16.1
  - tqdm
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn